version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=mydatabase
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    restart: always
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8081:80" # 映射到宿主机的 8081 端口
    environment:
      PMA_HOST: mysql      # 指向 MySQL 服务名称
      PMA_USER: root       # MySQL 用户名
      PMA_PASSWORD: rootpassword # MySQL 密码
    depends_on:
      - mysql
    restart: always

volumes:
  mysql_data: